"""
Core data models used throughout the Agentic AI framework.

This module defines the fundamental data structures that are passed between
components. All models use Python dataclasses for clarity, immutability hints,
and automatic __repr__ / __eq__ generation. These models form the "lingua franca"
of the framework - every LLM, agent, and tool communicates using these types.

Classes:
    Message     - A single message in a conversation (user, assistant, system, or tool).
    ToolCall    - A request from the LLM to invoke a specific tool with arguments.
    ToolResult  - The outcome of executing a tool, including success/failure status.
    AgentState  - A snapshot of an agent's internal state at a point in time.
    Document    - A text document with optional metadata, used in RAG pipelines.
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class Role(Enum):
    """
    Enumeration of possible message roles in a conversation.

    Each role indicates who authored the message, which determines how LLM
    providers format the message in their API calls.

    Attributes:
        SYSTEM:    Instructions that set the behavior/persona of the assistant.
        USER:      Messages from the human user.
        ASSISTANT: Messages generated by the AI assistant.
        TOOL:      Messages containing the result of a tool invocation.
    """

    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"


@dataclass
class Message:
    """
    Represents a single message in a multi-turn conversation.

    Messages are the primary unit of communication between the user, the LLM,
    and tools. They are collected in a list to form the conversation history
    that is sent to LLM providers for generating responses.

    Attributes:
        role:       The role of the message author (system, user, assistant, or tool).
        content:    The text content of the message. May be empty for tool-call-only
                    assistant messages.
        name:       Optional name identifier, used to distinguish between multiple
                    participants or to label tool results with the tool's name.
        tool_calls: A list of ToolCall objects if the assistant is requesting tool
                    invocations. Only populated when role is ASSISTANT.
        tool_call_id: The ID linking a tool result message back to the original
                      ToolCall that triggered it. Only populated when role is TOOL.
        metadata:   Arbitrary key-value pairs for provider-specific extensions
                    (e.g., token counts, latency, model version).

    Example:
        >>> msg = Message(role=Role.USER, content="What is 2 + 2?")
        >>> msg.role.value
        'user'
    """

    role: Role
    content: str = ""
    name: str | None = None
    tool_calls: list["ToolCall"] = field(default_factory=list)
    tool_call_id: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class ToolCall:
    """
    Represents a request from the LLM to invoke a specific tool.

    When an LLM determines that it needs to use a tool (e.g., a calculator,
    a web search API), it emits a ToolCall describing which tool to invoke
    and what arguments to pass. The framework's tool executor then processes
    these calls and returns ToolResult objects.

    Attributes:
        id:        A unique identifier for this tool call, used to correlate
                   the call with its result. Typically generated by the LLM provider.
        name:      The name of the tool to invoke (must match a registered tool).
        arguments: A dictionary of keyword arguments to pass to the tool's
                   execute method. Keys and values depend on the specific tool.

    Example:
        >>> call = ToolCall(id="call_1", name="calculator", arguments={"expression": "2+2"})
        >>> call.name
        'calculator'
    """

    id: str
    name: str
    arguments: dict[str, Any] = field(default_factory=dict)


@dataclass
class ToolResult:
    """
    Represents the outcome of executing a tool.

    After the framework invokes a tool in response to a ToolCall, it wraps
    the output in a ToolResult. This result is then formatted as a TOOL
    message and appended to the conversation history so the LLM can
    incorporate the tool's output into its next response.

    Attributes:
        tool_call_id: The ID of the ToolCall that triggered this result,
                      used to correlate requests and responses.
        output:       The string representation of the tool's output.
        success:      Whether the tool executed successfully. If False, the
                      output typically contains an error message.

    Example:
        >>> result = ToolResult(tool_call_id="call_1", output="4", success=True)
        >>> result.success
        True
    """

    tool_call_id: str
    output: str
    success: bool = True


class AgentStatus(Enum):
    """
    Enumeration of possible agent execution states.

    Tracks the lifecycle of an agent from initialization through completion
    or failure. Used by orchestrators and monitoring systems to understand
    what the agent is currently doing.

    Attributes:
        IDLE:      Agent is initialized but has not started processing.
        THINKING:  Agent is reasoning about the next action to take.
        ACTING:    Agent is executing a tool or sub-task.
        WAITING:   Agent is waiting for external input (e.g., human feedback).
        COMPLETED: Agent has finished its task successfully.
        FAILED:    Agent encountered an unrecoverable error.
    """

    IDLE = "idle"
    THINKING = "thinking"
    ACTING = "acting"
    WAITING = "waiting"
    COMPLETED = "completed"
    FAILED = "failed"


@dataclass
class AgentState:
    """
    A snapshot of an agent's internal state at a specific point in time.

    AgentState captures everything needed to understand, resume, or debug
    an agent's execution. It is updated after each reasoning/action step
    and can be serialized for persistence or monitoring.

    Attributes:
        status:           The current execution status of the agent.
        messages:         The full conversation history up to this point.
        current_step:     The zero-based index of the current reasoning step.
        max_steps:        The maximum number of steps before the agent stops.
        intermediate_results: A list of intermediate outputs collected during
                              multi-step execution (e.g., tool results, thoughts).
        metadata:         Arbitrary key-value pairs for framework-specific state
                          (e.g., plan steps for planning agents, sub-agent IDs
                          for hierarchical agents).

    Example:
        >>> state = AgentState(status=AgentStatus.THINKING, current_step=2, max_steps=10)
        >>> state.status.value
        'thinking'
    """

    status: AgentStatus = AgentStatus.IDLE
    messages: list[Message] = field(default_factory=list)
    current_step: int = 0
    max_steps: int = 10
    intermediate_results: list[Any] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class Document:
    """
    Represents a text document with optional metadata, used in RAG pipelines.

    Documents are the fundamental unit for retrieval-augmented generation (RAG).
    They are stored in vector databases after being converted to embeddings,
    and retrieved based on semantic similarity to a query. Each document
    carries metadata that can be used for filtering, attribution, or context.

    Attributes:
        content:  The text content of the document.
        metadata: Arbitrary key-value pairs providing additional context about
                  the document (e.g., source URL, creation date, author, chunk
                  index for documents split across multiple chunks).
        id:       An optional unique identifier. If not provided, the vector
                  store will typically generate one automatically.
        embedding: An optional pre-computed embedding vector. If provided, the
                   vector store can skip the embedding step during insertion.

    Example:
        >>> doc = Document(
        ...     content="Python is a programming language.",
        ...     metadata={"source": "wikipedia", "topic": "programming"},
        ... )
        >>> doc.metadata["source"]
        'wikipedia'
    """

    content: str
    metadata: dict[str, Any] = field(default_factory=dict)
    id: str | None = None
    embedding: list[float] | None = None
